// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oiaatpdvrfvgqsaqustf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9pYWF0cGR2cmZ2Z3FzYXF1c3RmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwMTEyOTEsImV4cCI6MjA3MzU4NzI5MX0.GA0b2OVVaWwnISxBxkBHNvcF-wUIuzNw9Xe7FMYGk4Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});